### ISSUE TITLE
FEATURES ROADMAP

### ISSUE THREAD

**Issue by piotrwitek** [piotrwitek/typesafe-actions-todo-app#6]
Features:
- [x] Router
- [ ] User Authentication
- [x] Feature Folders (Articles)
- [x] Application Services (Local Storage, Logger, Toast)
- [x] Typesafe API Clients
- [x] REST API Integration
- [x] CRUD Operations on Articles
- [ ] WebSockets Integration
- [ ] ...
